### ISSUE TITLE
Odd behavior with /misc/ URL

### ISSUE THREAD

**Issue by Alex-Keyes** [practicalli/spacemacs-gitbook#2]
After going through the whole book, I noticed at the bottom that the /misc/ section didn't lead me to anything and infact made some weird URLS, appending /misc/ to the url everytime I clicked misc in the sidebar. Here's an example URL:
```https://practicalli.github.io/spacemacs/misc/misc/misc/index.md```

I'm currently using google chrome running on Ubuntu 16.04.  Is this a bug with Gitbooks maybe?

**Comment by jr0cket** [comment]
Hello Alex, thanks for spotting this.  This situation seems to happen if the content is missing for a particular link in the navigation.  I've added the content pages for misc and resolved this issue.

Thank you.
(apologies for the slow reply, the book is now being activiely maintained again)
