### ISSUE TITLE
Searching a project with Ripgrep

### ISSUE THREAD

**Issue by jr0cket** [practicalli/spacemacs-gitbook#4]
https://github.com/BurntSushi/ripgrep

https://blog.burntsushi.net/ripgrep/

Note: only made this an issue to test adding of images (which works nicely, drag n drop too)

**Comment by jr0cket** [comment]
![24-pull-requests-of-xmas](https://user-images.githubusercontent.com/250870/45585070-4d0cd980-b8d6-11e8-98d6-72b17308eb91.png)

**Comment by jr0cket** [comment]
just testing adding of images with drag and drop

**Comment by practicalli-john** [comment]
Content added to https://practical.li/spacemacs/spacemacs-basics/working-with-projects/searching-projects.html
